name: Minecraft Needs Blood
description: Have you ever thought that Minecraft needs blood? No. Well have it anyway!
main: com.connorlinfoot.blood.Main
version: 3.0
commands:
  b:
    description: Main Command
  blood:
    description: Main Command
permissions:
  blood.toggle:
    description: Enable or Disable Blood
    default: op
  blood.old:
    description: Enable or Disable Old Style Blood
    default: op
  blood.reload:
    description: Reload blood config
    default: op